services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: "text2vec-transformers,generative-cohere"
      TRANSFORMERS_INFERENCE_API: "http://transformers-inference:8080"
    volumes:
      - ./data:/var/lib/weaviate
  transformers-inference:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    ports:
      - "8000:8080"
    environment:
      TRANSFORMERS_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
    deploy:
      resources:
        limits:
          memory: 2048M